
[[targets]]
name = "main"
dir = "../targetDir0/"
rulesLocation = "cfg"
rules = """
firefox
downloads
x downloads/notthere
downloads/notthere2
downloads/done
downloads/incomplete
"""

[[targets]]
name = "secondary"
dir = "../targetDir1/"
rulesLocation = "wc"
