
[[targets]]
name = "main"
type = "config-relative" # Allowed: "absolute", "config-relative".
dir = "../targetDir0/"
rules = """
firefox
downloads
downloads/done
downloads/incomplete
"""

[[targets]]

name = "secondary"
type = "config-relative"
dir = "../targetDir1/"
