#! /bin/bash

#> synopsis: TODO: write down.
#> type:     TODO: write down.
#> comment:  TODO: write down.

### WATCHCONF FILE EXAMPLE
# .                   ezN[ ]
# ./folderA/          z
# ./folderA/subA/     ez
# ./folderA/subB/     ez
# ./folderB/          zs
# ./folderB/fileA.txt e
# ./folderB/fileB.txt z
# ./folderC/          ez
# ./folderD/          t(txt,srt,sub,mp4)
# ./folderE/          t(mp3)
# TODO: make tests for these.

### WATCHCONF CODES (default linting: alert about broken rules).
# i             = ignore directory (ensure no rules are specified for directory subtree).
# o             = ensure directory does not contain any files (linting: delete fast, shred -zu , view+select+delete).
# O             = ensure directory does not contain any directories (linting: delete fast, shred -zu , view+select+delete).
# z             = ensure directory or file is empty (if it exists) (linting: delete fast, shred -zu , view+select+delete).
# e             = ensure directory or file exists (linting: create).
# s             = ensure all files have the same directory depth.
# T(e1[, en])   = ensure only the listed file types exist (as output by the linux command 'file').
# t(e1[, en])   = ensure only the listed file endings exist (eg. .pdf, .txt, .md, .srt, .sub, .mp4, .mp3, etc).
# d(N)          = ensure minimum directory depth of length N.
# D(N)          = ensure maximum directory depth of length N.
# f(N)          = ensure minimum file depth of length N.
# F(N)          = ensure maximum file depth of length N.
# w             = allow existence of Watchconf sub trees.
# W             = allow existence of Watchconf sub trees (recursively include them into the report).
# h             = allow existence of hidden directories and files.
# g             = allow existence of git direcotries.
# G             = treat git directories as final nodes.
# p[a-Z...]     = allow file names to only contain the specified characters.
# P[a-Z...]     = allow directory names to only contain the specified characters.
# n[a-Z...]     = like n, but disallows specified characters.
# N[a-Z...]     = like N, but disallows specified characters.
# x(N)          = ensure file size max.
# X(N)          = ensure file size min.
# y(N)          = ensure directory size max.
# Y(N)          = ensure directory size min.
# a             = forbid duplicated files.
# A             = forbid duplicated directories.
# b             = forbid duplicated file names.
# B             = forbid duplicated directory names.
# TODO: implement these.
# NOTE: maybe use other linter or C module to identify size of direcotries faster.

# TODO: implement checking the rules and alert (positive and negative).
# TODO: implement linting of rules.
# TODO: implement profiles or Watchconf files (ie user-specified profiles, in addition to pre-defined profiles: eg media store for videos and music, categorized media store, projects of restricted complexity).
# TODO: when everything else is coded: write some unit tests (eg by writing everything in python).
# TODO: when everything else is coded: implement algorithm to check for conflicting rules.
# TODO: decide what to do if a git repo includes a watchconf file.

subdirs='/tmp/subdirs'
rm -f "$subdirs"

function watch() {
	NL=$'\n'
	watch_dir="$1"
	cd "$watch_dir"
	conf=$(cat Watchconf)
	for d in */; do
		[ -L "${d%/}" ] && continue # exclude symlinks.
		echo "$d" >>"$subdirs"
	done
	echo CONF
	echo "$conf"
	echo SUBDIRS
	cat "$subdirs"
	echo END
}

function main() {
	while read watchdir; do
		watch "$watchdir"
	done <~/.watchcat_dirs
}

main
